### PR TITLE
Add support in pipelines for `Unsupervised` models for which `target_in_fit`  is `true`

### PR DESCRIPTION
**Pull request by ablaom**
This PR resolves https://github.com/JuliaAI/MLJ.jl/issues/1134.

An `Unsupervised` model that wants to buy into the new functionality must overload `MLJModelInterface.target_in_fit` to hold true. [Here](https://github.com/JuliaAI/MLJBase.jl/blob/4d37eedd5dce1d3f43409880181ae25b2394eb4e/test/composition/models/pipelines.jl#L711)'s an example from tests added in this PR. 

@EssamWisam Can you please confirm this resolves your issue with target encoding?

I have tested this PR with a local run of MLJ's integration tests.

### CODE REVIEW

**Comment by ablaom** [comment]
@EssamWisam A review would also be nice, if you have time to study the `Pipeline` code base enough to do that.

**Comment by EssamWisam** [comment]
I haven't studied the `Pipeline` code but looked closely at the changes (which are not that significant) and was able to make some sense out of them. Likewise, the tests seems to intuitive enough for me. I think this is on point.

**Comment by ablaom** [comment]
@EssamWisam Can you please confirm this PR resolves your issue with target encoding?

**Comment by EssamWisam** [comment]
@ablaom I tried to clone this branch of `MLJBase` and to dev it and `MLJTransforms` (after modifying it as needed) to further confirm but that was nontrivial for me:
```
Precompiling MLJTransforms
        Info Given MLJTransforms was explicitly requested, output will be shown live 
WARNING: Method definition target_in_fit(Type) in module StatisticalTraits at [/Users/essamwisam/.julia/packages/StatisticalTraits/4sp0J/src/StatisticalTraits.jl:149](https://file+.vscode-resource.vscode-cdn.net/Users/essamwisam/.julia/packages/StatisticalTraits/4sp0J/src/StatisticalTraits.jl:149) overwritten in module MLJTransforms at [/Users/essamwisam/Documents/GitHub/MLJTransforms/src/target_encoding/interface_mlj.jl:118](https://file+.vscode-resource.vscode-cdn.net/Users/essamwisam/Documents/GitHub/MLJTransforms/src/target_encoding/interface_mlj.jl:118).
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
  ? MLJTransforms
[ Info: Precompiling MLJTransforms [23777cdb-d90c-4eb0-a694-7c2b83d5c1d6]
WARNING: Method definition target_in_fit(Type) in module StatisticalTraits at [/Users/essamwisam/.julia/packages/StatisticalTraits/4sp0J/src/StatisticalTraits.jl:149](https://file+.vscode-resource.vscode-cdn.net/Users/essamwisam/.julia/packages/StatisticalTraits/4sp0J/src/StatisticalTraits.jl:149) overwritten in module MLJTransforms at [/Users/essamwisam/Documents/GitHub/MLJTransforms/src/target_encoding/interface_mlj.jl:118](https://file+.vscode-resource.vscode-cdn.net/Users/essamwisam/Documents/GitHub/MLJTransforms/src/target_encoding/interface_mlj.jl:118).
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
[ Info: Skipping precompilation since __precompile__(false). Importing MLJTransforms [23777cdb-d90c-4eb0-a694-7c2b83d5c1d6].
```
Thus, I can only say I believe this would solve the issue but can't be absolutely certain.

**Comment by ablaom** [comment]
@EssamWisam To help me diagnose, what exactly do you have at line 118 of MLJTransforms/src/target_encoding/interface_mlj.jl ? This will be your overloading of `target_in_fit`, the source of the complaint.

**Comment by EssamWisam** [comment]
I passed an incorrect argument instead of `MMI.target_in_fit(::Type{<:TargetEncoder}) = true` after fixing it works as expected.

**Pull request merged**
