### PR TITLE
When constructing a `TransformedTargetModel`, allow the user to override the `target_scitype`, `predict_scitype`, and `prediction_type` traits

### PR DESCRIPTION
**Pull request by DilumAluthge**
For example, this will allow the user to take a `Deterministic` regression model and transform it into a `Probabilistic` binary classification model.

TODO before merging:
- [ ] Remove the `evotrees.jl` tests.
- [ ] Add some simpler tests.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@ablaom @OkonSamuel This is now ready to review.

Instead of specifying the abstract type, the user instead specifies some traits, and we infer the appropriate abstract type based on those traits. Specifically, the user can provide the following three traits:
1. `target_scitype`
2. `predict_scitype`
3. `prediction_type`

Right now, I'm testing this PR by using an example drawn from EvoTrees.jl, which was the original motivation for this PR. I'm fine with keeping that test, but I realize that EvoTrees.jl is a heavy dependency, so I would also be fine with removing the EvoTrees-based tests and instead putting in some more lightweight tests.

Also, right now, I have MLJ.jl as a test dependency; obviously we want to get rid of that.

**Review by ablaom — COMMENTED** [review]
Thanks @DilumAluthge  for spending time with `TransformedTargetModel`. There is one problem, for which you are not really to blame, which involves an issue we have resolved in other wrappers, but not here, which has led you to be misled. 

 In your PR you make `target_scitype` a type parameter of `TransformedModel`, but in fact the `target_scitpye` of this wrapper (and other model wrappers like, say, [`IteratedModel`](https://github.com/JuliaAI/MLJIteration.jl/blob/7d063f9c6eb1c8a8956426bf522c0c1d5839aab3/src/traits.jl#L14)) cannot be a parameter, because in general it cannot be determined from the *type* of the atomic model `model`, only from a model *instance*, and the user is permitted to mutate the `model` in ways which change its `target_scitype`. An example is when the atomic `model` is a pipeline model. See [this comment](https://github.com/JuliaAI/MLJBase.jl/blob/94c3d10b72884551b72c2a3d1a7d037964fb651e/src/composition/models/pipelines.jl#L3). At present the only guarantee is that the `abstract_type` of `model` will not change. (Even this might change in the longer term if we discard the abstract type hierarchy).

Traits were initially defined at the level of types, because this was very natural from the point of view of the model registry. So, in fact, every model in the registry has a `target_scitype` that is known from its type. However,  composite models complicate the story: one may want (in "architecture search", say) to mutate model components in ways which change the `target_scitype` (or other traits) (this could be as mild as `OrderedFactor{2}` -> `OrderedFactor`). So, moving forward, outside of the registry, traits should only be called on instances, and only implemented for types when safe to do so (a fallback for every trait gets the instance trait from the type trait).

Perhaps you have a better idea, but I cannot help but feel we are working very hard to resolve an issue here than will disappear in a future no-abstract-type refactoring of MLJ.  But it's also not clear how much support there is for that refactoring, which itself will be the most disruptive so far. 

Perhaps we can keep he type parameters you have added here but have them fallback to `Nothing` when the user does not specify the `traits` dictionary. Then the traits for the wrapped model are determined by their values on instances for the atomic model if the type parameters are `Nothing` and otherwise get them from the type parameters. But this seems very hacky, and difficult to understand/maintain later.

I will today have a look at a workaround for the original issue you raised on Slack -  it seems to me that `check_measures=false` is not toggling all checks off, as it should. And will cross-reference here for you to consider as an alternative resolution to your problem.

**Comment by ablaom** [comment]
https://github.com/JuliaAI/MLJBase.jl/pull/748

**Comment by DilumAluthge** [comment]
Closing in favor of https://github.com/JuliaAI/MLJBase.jl/pull/748 and https://github.com/JuliaAI/MLJBase.jl/issues/760

**Pull request closed without merging**
