### PR TITLE
Test suite: modify some uses of `deepcopy`

### PR DESCRIPTION
**Pull request by DilumAluthge**
This is necessary to get tests passing on Julia nightly.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@ablaom This is now ready for review.

The changes in this PR are necessary to get the MLJBase tests passing on the latest Julia nightly. With these changes, I am able to get tests passing on nightly.

After this PR has been merged, I'll finish up the PR to run CI on Julia nightly (https://github.com/JuliaAI/MLJBase.jl/pull/822).

**Review by ablaom — APPROVED** [review]
Thanks @DilumAluthge. Looks good.

But I am worried about having a future Julia release that is not tolerant of deep copies? Is this just a performance issue or will the code here actually fail in future Julia releases?

**Comment by DilumAluthge** [comment]
I think this is a Julia bug, specifically a regression from 1.7.3 to 1.8.0. I'll open an issue.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/julia/issues/46405

**Comment by ablaom** [comment]
RIght. Good job diagnosing. I think finding a Julia bug should at least get you free a T-shirt or something 😄

**Pull request merged**
