### PR TITLE
Fix typo probab i listic

### PR DESCRIPTION
**Pull request by svilupp**
As part of the JuliaCon hackathon, I've fixed some typos that I've noticed in the docs - spelling of `probabilistic` in this case.

No changes made to active code - only docs/comments.

### CODE REVIEW

**Comment by ablaom** [comment]
Looks like you forgot to commit a new file, meta_utilities.jl?

**Comment by svilupp** [comment]
> Looks like you forgot to commit a new file, meta_utilities.jl?

Yes, that's what the error says but I'm a bit stunned as to why that happens. 
I've merely changed a docstring and it was a clean fork of dev branch (which also doesn't have the requested file).

I've looked at another example in /src/measures/meta_utilities.jl, but it's not entirely clear to me what it's trying to do (it's a new pattern for me).

Are you suggesting that I should create a new file or would you expect for the file to already be there?

**Comment by ablaom** [comment]
I'm not sure what is going on here. Your first two commits look good. But your third commit looks much more complicated than  modifying a few doc-strings. Can you say more about it? Are your re-organizing content? It's not looking straightforward to review. Perhaps you want to revert to the previous commit and start over??

**Comment by svilupp** [comment]
> I'm not sure what is going on here. Your first two commits look good. But your third commit looks much more complicated than modifying a few doc-strings. Can you say more about it? Are your re-organizing content? It's not looking straightforward to review. Perhaps you want to revert to the previous commit and start over??

Not at all. I don't recognize it, so it must have been some accidental change when using Github Online - sorry about that!

I've just reverted, so, hopefully, it's will pass no.

**Comment by ablaom** [comment]
@svilupp Is this ready to review yet?

**Comment by svilupp** [comment]
> @svilupp Is this ready to review yet?

Yes, it is. It's just the three typos of the word `probabilistic`.

**Review by ablaom — APPROVED** [review]
Looks good to go, thanks @svilupp.

**Pull request merged**
